version: '3.8'
services:
   server:
      hostname: homebridge
      image: homebridge:latest
      restart: always
      network_mode: host
      ports:
         - target: 51826
           published: 51826
           protocol: tcp
           mode: host
      volumes:
         - type: bind
           source: /etc/localtime
           target: /etc/localtime
         - type: bind
           source: /etc/timezone
           target: /etc/timezone
         - type: bind
           source: $PWD/data
           target: /opt/homebridge/data

